### ISSUE TITLE
Cannot run in standalone mode

### ISSUE THREAD

**Issue by Mikilll94** [react-microfrontends/planets#19]
Hello,
Is it possible to run this project in standalone mode? Right now if run `pnpm start:standalone` I receive the following error:

![Screenshot 2021-03-12 at 16 33 34](https://user-images.githubusercontent.com/17653648/110961987-b4ddf700-8350-11eb-8f4e-144191f6bbb7.png)

Is it possible to add import map for the `api` project in development mode?

**Comment by joeldenning** [comment]
Hi @Mikilll94, good question. Yes this is possible via the standalone plugin's `importMapUrl` option. See https://github.com/single-spa/standalone-single-spa-webpack-plugin#usage

I've fixed standalone mode for this project in https://github.com/react-microfrontends/planets/commit/41ba0aaf9005b5300cc28ad5f4eac024eae06e2b -  you can see there for how to use it. Standalone mode now works if you go to http://localhost:8080/planets.
